site_name: awesome-gee-community-datasets
site_description: Community Datasets in Google Earth Engine
site_author: Samapriya Roy
site_url: https://github.com/samapriya

# Repository
repo_name: awesome-gee-community-datasets
repo_url: https://github.com/samapriya/awesome-gee-community-datasets

# Copyright
copyright: 'Copyright &copy; 2021 - 2022 Samapriya Roy'


# Configuration
theme:
  name: 'material'

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Google Sans
    code: Regular
  favicon: assets/favicon.png
  icon:
    logo: logo

# Options
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/samapriya
    - icon: fontawesome/brands/medium
      link: https://medium.com/@samapriyaroy
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/samapriyaroy
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/samapriya

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde



# Page tree
nav:
  - Introduction: index.md
  - Population & Socioeconomic:
    - High Resolution Settlement Layers: projects/hrsl.md
    - GPW Version 4 Admin Units: projects/GPWv4.md
    - West Africa Coastal Vulnerability Mapping: projects/wacvm.md
    - Relative Wealth Index (RWI): projects/rwi.md
    - Social Connectedness Index (SCI): projects/sci.md
  - Geophysical:
    - Geomorpho90m Geomorphometric Layers: projects/geomorpho90.md
    - Soil Grids 250m v2.0: projects/isric.md
    - iSDAsoil Predicted Soil Properties for Africa 30m: projects/isda.md
    - Polaris 30m Probabilistic Soil Properties US: projects/polaris.md
    - HiHydroSoil v2.0 layers: projects/hihydro_soil.md
    - Soil Organic Carbon Stocks & Trends South Africa: projects/soc.md
    - Bare Earth’s Surface Spectra 1980-2019: projects/bss.md
    - Global Mangrove Project: projects/mangrove.md
  - Land Use and Land Cover:
    - Mapbiomas Annual land cover and use maps: projects/mapbiomas.md
    - West Africa Land Use Land Cover: projects/wa_lulc.md
    - South African National Land Cover 2018: projects/sa_nlc2018.md
    - Continental-scale land cover mapping at 10 m resolution over Europe: projects/elc.md
    - ESRI 2020 Global Land Use Land Cover from Sentinel-2: projects/esrilc2020.md
    - Oil Palm Plantation (Indonesia, Malaysia, Thailand) 1984-2017: projects/oil-palm.md
  - Hydrology:
    - Global Shoreline Dataset: projects/shoreline.md
    - OSM Water Layer Surface Waters in OpenStreetMap: projects/osm_water.md
    - Global 30m Height Above the Nearest Drainage: projects/hand.md
    - Global River Width from Landsat (GRWL): projects/grwl.md
    - Global coastal rivers and environmental variables: projects/rivermouth.md
    - Global River Deltas and vulnerability: projects/river_deltas.md
    - General Bathymetric Chart of the Oceans (GEBCO): projects/gebco.md
  - Agriculture, Vegetation and Forestry:
    - Landfire Mosaics LF v2.0.0: projects/landfire.md
    - Vegetation dryness for western USA: projects/veg_dry.md
    - Rangeland Analysis Platform layers: projects/rap.md
    - NASA Harvest Layers: projects/harvest.md
    - Benchmark maps Secondary Forest Brazil: projects/secondary_forest.md
    - Global irrigation areas (2001 to 2015): projects/global_irrigation.md
  - Utilities:
    - Global Power: projects/global_power.md
    - Facebook Electrical Distribution Grid Maps: projects/electric_grid.md
    - Global Roads Inventory Project: projects/grip.md
    - Global Mining Areas and Validation Datasets: projects/global_mining.md
    - Global Healthsites Mapping Project: projects/health_sites.md
  - EarthEnv Biodiversity ecosystems & climate Layers:
    - Global Consensus Landcover: projects/gcl.md
    - Global Freshwater Variables: projects/gfv.md
    - Global Habitat Heterogeneity: projects/ghh.md
    - Global 1-km Cloud Cover: projects/gcc.md
  - Weather, Climate and Events:
    - Global Reference Evapotranspiration Layers: projects/et0.md
    - Global Aridity Index: projects/ai0.md
    - Current and projected climate data for North America (CMIP6 scenarios): projects/aogcm_cmip6.md
    - United States Drought Monitor Layers: projects/usdm.md
    - Global Fire Atlas (2003-2016): projects/gfa.md
    - Global large flood events <Dartmouth Flood Observatory> (1985-2016) : projects/flood.md
    - Global Landslide Catalog <NASA Goddard> (1970-2019): projects/landslide.md
  - License: license.md
